(function(){
  const URL_VER = Date.now(); // always force fresh fetch
  const XLSX_FILE = new URL(`./data.xlsx?v=${URL_VER}`, location.href).toString();
  const SHEET_NODES='ChainNodes', SHEET_LINKS='ChainLinks', SHEET_STOCKS='ChainStocks', SHEET_REVENUE='Revenue';
  const svg = d3.select('#sc-svg');
  const listEl = document.querySelector('#sc-stock-list');
  const listTitle = document.querySelector('#sc-list-title');
  const state = { inited:false, nodes:[], links:[], stocksByStage:new Map(), stockToStages:new Map(), revenueRows:[], colMap:{}, months:[], byCodeName:new Map(), sim:null, nodeSel:null, linkSel:null };
  document.addEventListener('DOMContentLoaded', async()=>{ try{ const wb=await loadWorkbook(); buildData(wb); buildChart(); bindExternalControls(); state.inited=true; } catch(e){ console.error(e); if(svg.node()) svg.append('text').attr('x',20).attr('y',30).attr('fill','#e11d48').text('供應鏈資料載入失敗：'+e.message); } });
  async function loadWorkbook(){ const r=await fetch(XLSX_FILE,{cache:'no-store'}); if(!r.ok) throw new Error('讀取 data.xlsx 失敗（HTTP '+r.status+'）'); const buf=await r.arrayBuffer(); return XLSX.read(buf,{type:'array'}); }
  const COL_RE={ YoY:/^(\d{4})[\/年-]?\s*(\d{1,2})\s*單月合併營收\s*年[成增]長\s*[\(（]?(?:%|％)[\)）]?$/i, MoM:/^(\d{4})[\/年-]?\s*(\d{1,2})\s*單月合併營收\s*月[變增]動\s*[\(（]?(?:%|％)[\)）]?$/i };
  function toHalfWidth(s){ return String(s||'').replace(/[０-９Ａ-Ｚａ-ｚ]/g,ch=>String.fromCharCode(ch.charCodeAt(0)-0xFEE0)); }
  function normText(s){ return String(s==null?'':s).replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\u3000/g,' ').replace(/\s+/g,' ').trim(); }
  function normCode(s){ return toHalfWidth(String(s||'')).replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\s+/g,'').trim(); }
  function displayPct(v){ if(v==null||!isFinite(v)) return '—'; const s=v.toFixed(1)+'%'; return v>=0?('+'+s):s; }
  function buildData(wb){ const wsN=wb.Sheets[SHEET_NODES], wsL=wb.Sheets[SHEET_LINKS], wsS=wb.Sheets[SHEET_STOCKS], wsR=wb.Sheets[SHEET_REVENUE]; if(!wsN||!wsL||!wsS) throw new Error('缺少工作表：'+[!wsN&&SHEET_NODES,!wsL&&SHEET_LINKS,!wsS&&SHEET_STOCKS].filter(Boolean).join(',')); if(wsR){ const rowsHeader=XLSX.utils.sheet_to_json(wsR,{header:1,blankrows:false}); const header=Array.isArray(rowsHeader)&&rowsHeader.length?rowsHeader[0]:[]; const found=new Set(); const colMap={}; header.forEach(raw=>{ if(!raw) return; const h=normText(String(raw)); let m=h.match(COL_RE.YoY); if(m){ const ym=m[1]+String(m[2]).padStart(2,'0'); (colMap[ym]??={}).YoY=raw; found.add(ym); return;} m=h.match(COL_RE.MoM); if(m){ const ym=m[1]+String(m[2]).padStart(2,'0'); (colMap[ym]??={}).MoM=raw; found.add(ym);} }); state.colMap=colMap; state.months=Array.from(found).sort((a,b)=>b.localeCompare(a)); state.revenueRows=XLSX.utils.sheet_to_json(wsR,{defval:null}); const CODE_FIELDS=['個股','代號','股票代碼','股票代號','公司代號','證券代號']; const NAME_FIELDS=['名稱','公司名稱','證券名稱']; const sample=state.revenueRows[0]||{}; const codeKey=CODE_FIELDS.find(k=>k in sample)||CODE_FIELDS[0]; const nameKey=NAME_FIELDS.find(k=>k in sample)||NAME_FIELDS[0]; state.revenueRows.forEach(r=>{ const code=normCode(r[codeKey]); const name=normText(r[nameKey]); if(code) state.byCodeName.set(code,name); }); }
    state.nodes = XLSX.utils.sheet_to_json(wsN,{defval:null}).map(r=>({id:Number(r['節點ID']), name:String(r['名稱']||''), order:Number(r['順序']||r['節點ID'])})).filter(d=>Number.isFinite(d.id)&&d.name);
    state.links = XLSX.utils.sheet_to_json(wsL,{defval:null}).map(r=>({source:Number(r['source']), target:Number(r['target'])})).filter(e=>Number.isFinite(e.source)&&Number.isFinite(e.target));
    const stocksByStage=new Map(), stockToStages=new Map();
    XLSX.utils.sheet_to_json(wsS,{defval:null}).forEach(r=>{ const sid=Number(r['節點ID']); const code=normCode(r['個股']); let name=normText(r['名稱']||''); if(!name&&code&&state.byCodeName.has(code)) name=state.byCodeName.get(code); if(!Number.isFinite(sid)||!code) return; if(!stocksByStage.has(sid)) stocksByStage.set(sid,[]); stocksByStage.get(sid).push({code,name}); if(!stockToStages.has(code)) stockToStages.set(code,[]); stockToStages.get(code).push(sid); });
    state.stocksByStage=stocksByStage; state.stockToStages=stockToStages; }
  function getMetricValueByCode(code, month, metric){ const row=state.revenueRows.find(r=>{ const v=r['個股']??r['代號']??r['股票代碼']??r['股票代號']??r['公司代號']??r['證券代號']; return normCode(v)===code; }); if(!row||!month||!metric) return null; const col=(state.colMap[month]||{})[metric]; if(!col) return null; let v=row[col]; if(v==null||v==='') return null; if(typeof v==='string') v=v.replace('%','').replace('％','').trim(); v=Number(v); return Number.isFinite(v)?v:null; }
  function buildChart(){
    if(state.nodes.length===0||state.links.length===0){
      const el = document.getElementById('sc-right') || document.getElementById('supplychain-vis');
      if(el){ el.innerHTML = '<div style="padding:16px;color:#eab308">⚠️ 找不到節點或連線。請確認 data.xlsx 的 ChainNodes/ChainLinks 是否有資料，且欄名為：節點ID/名稱/順序、source/target。<br/>目前偵測：nodes='+state.nodes.length+'、links='+state.links.length+'</div>'; }
    }
 svg.selectAll('*').remove(); svg.append('defs').append('marker').attr('id','sc-arrow').attr('viewBox','0 -5 10 10').attr('refX',22).attr('refY',0).attr('markerWidth',6).attr('markerHeight',6).attr('orient','auto').append('path').attr('d','M0,-5L10,0L0,5').attr('fill','#bdbdbd'); const g=svg.append('g').attr('class','sc-g'); const linkSel=g.selectAll('.sc-link').data(state.links).enter().append('line').attr('class','sc-link'); const nodeSel=g.selectAll('.sc-node').data(state.nodes).enter().append('g').attr('class','sc-node').on('click',(_,d)=>{ highlightStages([d.id]); renderListForStage(d.id); }).call(d3.drag().on('start',(ev,d)=>{ if(!ev.active) state.sim.alphaTarget(0.3).restart(); d.fx=d.x; d.fy=d.y; }).on('drag',(ev,d)=>{ d.fx=ev.x; d.fy=ev.y; }).on('end',(ev,d)=>{ if(!ev.active) state.sim.alphaTarget(0); d.fx=null; d.fy=null; })); nodeSel.append('circle').attr('r',22); nodeSel.append('text').attr('text-anchor','middle').attr('dy',-32).text(d=>d.name); const xScale=d3.scaleLinear().domain(d3.extent(state.nodes,d=>d.order)).range([80,920]); state.sim=d3.forceSimulation(state.nodes).force('link',d3.forceLink(state.links).id(d=>d.id).distance(120)).force('charge',d3.forceManyBody().strength(-450)).force('center',d3.forceCenter(500,310)).force('x',d3.forceX(d=>xScale(d.order)).strength(0.45)).force('y',d3.forceY(310).strength(0.06)); state.sim.on('tick',()=>{ linkSel.attr('x1',d=>d.source.x).attr('y1',d=>d.source.y).attr('x2',d=>d.target.x).attr('y2',d=>d.target.y); nodeSel.attr('transform',d=>`translate(${d.x},${d.y})`); }); state.nodeSel=nodeSel; state.linkSel=linkSel; const firstId=state.nodes[0]?.id; if(firstId!=null) renderListForStage(firstId); }
  function renderListForStage(stageId){ const month=document.querySelector('#monthSelect')?.value || state.months[0] || null; const metric=document.querySelector('#metricSelect')?.value || 'MoM'; const list=state.stocksByStage.get(stageId)||[]; listTitle.textContent='📌 '+(state.nodes.find(n=>n.id===stageId)?.name||'選擇節點')+'：相關概念股'; if(list.length===0){ listEl.innerHTML='<li>（此節點尚無資料）</li>'; return; } const enriched=list.map(s=>({ ...s, v:getMetricValueByCode(s.code, month, metric) })).sort((a,b)=>((b.v==null?-Infinity:b.v)-(a.v==null?-Infinity:a.v))); listEl.innerHTML=enriched.map(s=>{ const pct=s.v==null?'—':displayPct(s.v); return `<li><span class="code">${s.code}</span><span>${(s.name||'')}</span><span class="chip">${month?(`${month.slice(0,4)}/${month.slice(4,6)}`:'--')} · ${metric}</span><span style="margin-left:6px;">${pct}</span><button data-code="${s.code}" title="以此個股為主角">查看</button></li>`; }).join(''); listEl.querySelectorAll('button[data-code]').forEach(btn=>{ btn.addEventListener('click',()=>{ const code=btn.getAttribute('data-code'); window.dispatchEvent(new CustomEvent('stockSelected',{detail:{code}})); }); }); }
  function highlightStages(stageIds){ const set=new Set(stageIds||[]); state.nodeSel.classed('highlight', d=> set.has(d.id)); state.linkSel.attr('stroke', d=> (set.has(d.source.id)||set.has(d.target.id)) ? '#666' : '#bdbdbd').attr('stroke-width', d=> (set.has(d.source.id)||set.has(d.target.id)) ? 3 : 1.5); }
  function bindExternalControls(){ ['monthSelect','metricSelect'].forEach(id=>{ const el=document.getElementById(id); if(el) el.addEventListener('change',()=>{ const highlighted=document.querySelector('.sc-node.highlight')?._data?.id ?? state.nodes[0]?.id; if(highlighted!=null) renderListForStage(highlighted); }, {passive:true}); }); state.nodeSel?.each(function(d){ this._data=d; }); }
  function updateSupplyChainByTicker(code){ if(!state.inited) return; const stages=state.stockToStages.get(code)||[]; highlightStages(stages); if(stages.length>0) renderListForStage(stages[0]); document.getElementById('sc-section')?.scrollIntoView({behavior:'smooth', block:'start'}); }
  window.updateSupplyChainByTicker = updateSupplyChainByTicker;
})();
